name: eatinpal
description: "EatinPal - Your personal calorie & nutrition tracker"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^9.2.1

  # Networking
  dio: ^5.7.0

  # Navigation
  go_router: ^17.2.0

  # Functional Programming
  fpdart: ^1.1.0

  # Code Generation (annotations)
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  # Environment
  flutter_dotenv: ^6.0.0

  # Local Storage
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Code Generation
  build_runner: ^2.4.13
  freezed: ^3.2.5
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - .env
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
    - family: Epilogue
      fonts:
        - asset: assets/fonts/Epilogue-VariableFont_wght.ttf
